version: "3.9"
services:
  api:
    build: .
    container_name: periodic-table-api
    environment:
      NODE_ENV: production
      PORT: 3000
    expose:
      - "3000"
    command: ["node", "src/server.js"]

  nginx:
    image: nginx:alpine
    container_name: periodic-table-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
